Prepare release (1.91)
Ignore-this: 254f7af370700be1568d4d4819eef150

darcs-hash:20110408181245-da4f2-6e22ab2f045dc917b0cd7bf969076526e763416e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -88,9 +88,9 @@ set_defaults () {
 }
 
 set_defaults
-my_pwd=`dirname $0`
-version=`head -n 1 $my_pwd/VERSION`
-full_pwd=`pwd`
+my_pwd=$(dirname $0)
+version=$(head -n 1 $my_pwd/VERSION)
+full_pwd=$(pwd)
 
 ########################################################################
 ## Option parsing
@@ -109,7 +109,7 @@ print_options () {
 	for opt in $eoptions; do
 		e="o=\$enable_$opt"
 		eval "$e"
-		uopt=`echo $opt | sed -e 's/_/-/g'`
+		uopt=$(echo $opt | sed -e 's/_/-/g')
 		if [ $o -gt 0 ]; then
 			echo "    --enable-$uopt"
 		else
@@ -119,7 +119,7 @@ print_options () {
 	for opt in $woptions; do
 		e="o=\$with_$opt"
 		eval "$e"
-		uopt=`echo $opt | sed -e 's/_/-/g'`
+		uopt=$(echo $opt | sed -e 's/_/-/g')
 		if [ $o -gt 0 ]; then
 			echo "    --with-$uopt"
 		else
@@ -206,25 +206,25 @@ echo "Welcome to Eliom version $version" >&2
 while [ "$#" -gt 0 ]; do
 	case "$1" in
 		--enable-*)
-			opt=`echo "$1" | sed -e 's/--enable-//' -e 's/-/_/g'`
+			opt=$(echo "$1" | sed -e 's/--enable-//' -e 's/-/_/g')
 			check_eopt "$opt"
 			eval "enable_$opt=2"
 			shift
 			;;
 		--disable-*)
-			opt=`echo "$1" | sed -e 's/--disable-//' -e 's/-/_/g'`
+			opt=$(echo "$1" | sed -e 's/--disable-//' -e 's/-/_/g')
 			check_eopt "$opt"
 			eval "enable_$opt=-1"
 			shift
 			;;
 		--with-*)
-			opt=`echo "$1" | sed -e 's/--with-//' -e 's/-/_/g'`
+			opt=$(echo "$1" | sed -e 's/--with-//' -e 's/-/_/g')
 			check_wopt "$opt"
 			eval "with_$opt=2"
 			shift
 			;;
 		--without-*)
-			opt=`echo "$1" | sed -e 's/--without-//' -e 's/-/_/g'`
+			opt=$(echo "$1" | sed -e 's/--without-//' -e 's/-/_/g')
 			check_wopt "$opt"
 			eval "with_$opt=-1"
 			shift
@@ -289,10 +289,10 @@ check_binary ocamlc "See: http://www.ocaml.org/"
 check_ocamlversion () {
 
   echo -n "Checking for OCaml version... "
-  version=`ocamlc -version`
+  version=$(ocamlc -version)
   echo $version
-  n1=`echo $version | sed 's/^\([0-9][0-9]*\)\..*$/\1/'`
-  n2=`echo $version | sed 's/^[0-9][0-9]*\.\([0-9][0-9]*\)\..*$/\1/'`
+  n1=$(echo $version | sed 's/^\([0-9][0-9]*\)\..*$/\1/')
+  n2=$(echo $version | sed 's/^[0-9][0-9]*\.\([0-9][0-9]*\)\..*$/\1/')
   # n3=`echo $version | sed 's/^[0-9][0-9]*\.[0-9][0-9]*\.\([0-9][0-9]*\)\..*$/\1/'`
   if [ $n1 -eq 3 ] && [ $n2 -lt 12 ]; then
       echo;
@@ -302,11 +302,30 @@ check_ocamlversion () {
 
 }
 
+check_ocsigenserverversion () {
+
+  echo -n "Checking for ocsigenserver version... "
+  version=$(ocamlfind query ocsigenserver -l | grep version: | awk '{ print $2 }')
+  echo $version
+  n1=$(echo $version | sed 's/^\([0-9][0-9]*\)\..*$/\1/')
+  n2=$(echo $version | sed 's/^[0-9][0-9]*\.\([0-9][0-9]*\).*$/\1/')
+  # n3=`echo $version | sed 's/^[0-9][0-9]*\.[0-9][0-9]*\.\([0-9][0-9]*\)\..*$/\1/'`
+  if [ $n1 -eq 1 ] && [ $n2 -lt 91 ]; then
+      echo;
+      echo "Ocsigenserver >= 1.91 is required. Aborting.";
+      exit 1;
+  fi
+
+}
+
 check_ocamlversion
 
 check_binary ocamlfind "See: http://projects.camlcity.org/projects/findlib.html"
 
-check_library deriving-ocsigen "See: ???"
+check_library ocsigenserver "See: http://ocsigen.org/ocsigenserver/"
+check_ocsigenserverversion
+
+check_library deriving-ocsigen "See: https://github.com/hnrgrgr/deriving"
 
 check_binary js_of_ocaml "See: http://ocsigen.org/js_of_ocaml"
 check_library js_of_ocaml.deriving "Missing support for deriving-ocsigen in js_of_ocaml"
@@ -337,7 +356,6 @@ echo
 echo "Effective options:"
 print_options
 echo
-
 
 #Convert 0/1 values to YES/NO
 if [ $enable_debug -gt 0 ] ; then
