Deflatemod -- compress pages
Use --enable-camlzip and modify your ocsigen.conf if you want use this module.

*** NATIVE MODE WARNING ***
If you build in native mode, be aware that camlzip provides a .cmxa file,
but ocsigen.opt.local will include a path to a .cmxs file. You should do
whatever needs to be done in order to fix this (i'm not a native mode guru,
sorry).

darcs-hash:20070922160351-bd3f0-13864fc5bf8ab8d4b4d82d06d52c898ae2433769

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -49,7 +49,8 @@ set_defaults () {
     enable_ocamlduce=0
     enable_newocamlnet=1
     enable_sqlite=1
-    enable_dbm=1
+    enable_camlzip=0
+	enable_dbm=1
     prefix="/usr/local"
     bindir=""
     examplesdir=""
@@ -83,9 +84,10 @@ ehelp_ocamlduce="Enable/disable Ocamlduce for typing pages (requires ocamlduce t
 ehelp_newocamlnet="Use new/old versions of Ocamlnet (>= 2.0)"
 ehelp_sqlite="Compile ocsipersist with SQLite for persistent storage (default)"
 ehelp_dbm="Compile ocsipersist with DBM for persistent storage"
+ehelp_camlzip="Compile deflatemod module (requires camlzip); not loaded by default"
 
 ## Which options exist? eoptions for enable/disable, woptions for with/without:
-eoptions="debug bytecode nativecode ocamlduce newocamlnet sqlite dbm"
+eoptions="debug bytecode nativecode ocamlduce newocamlnet sqlite dbm camlzip"
 woptions=""
 
 
@@ -471,6 +473,23 @@ fi
 
 
 ######################################################################
+# Check Camlzip
+
+if [ "$enable_camlzip" -gt 0 ]; then
+    printf "%s" "Checking for camlzip... "
+    if ocamlfind query camlzip >/dev/null 2>/dev/null; then
+        echo "found"
+    else
+        echo "not found"
+        echo "Required library sqlite3 not found!"
+        exit 1
+    fi
+
+    camlzipdir=`ocamlfind query camlzip`
+fi
+
+
+######################################################################
 # Check whether OCaml version is > 3.9
 version=`ocamlc -version`
 ocamlversion=`n1=${version%%.[0-9][0-9].[0-9]}; \
@@ -546,6 +565,12 @@ if [ $enable_sqlite -gt 0 ] ; then
 else
 	enable_sqlite="NO"
 fi
+if [ $enable_camlzip -gt 0 ] ; then
+	enable_camlzip="YES"
+else
+	enable_camlzip="NO"
+fi
+
 
 
 
@@ -637,6 +662,12 @@ COMMANDPIPE=$root$commandpipe
 
 # The directory where ocamlsqlite3 is installed
 OCAMLSQLITE3DIR=$ocamlsqlite3dir
+
+# The directory where camlzip is installed
+CAMLZIPDIR=$camlzipdir
+
+# Do you want deflatemod? (requires camlzip)
+CAMLZIP=$enable_camlzip
 
 # Do you want ocsipersist with sqlite?
 OCSIPERSISTSQLITE=$enable_sqlite
