configure: checking for netstring and obrowser
Ignore-this: 621ee6ed4c1b3f26d97717b605f92df5

darcs-hash:20100105193039-1b86b-47c4308f58727162bad88070578b58acf438e500

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -529,6 +529,30 @@ else
     exit 1
 fi
 
+######################################################################
+# Check Obrowser
+
+printf "%s" "Checking for obrowser... "
+if ocamlfind query obrowser >/dev/null 2>/dev/null; then
+    echo "found"
+else
+    echo "not found"
+    echo "Required dependency obrowser not found!"
+    exit 1
+fi
+
+######################################################################
+# Check Ocamlnet
+
+printf "%s" "Checking for netstring... "
+if ocamlfind query netstring >/dev/null 2>/dev/null; then
+    echo "found"
+else
+    echo "not found"
+    echo "Required library netstring not found!"
+    exit 1
+fi
+
 
 ######################################################################
 # Check SQLITE3
