Adding dendendency check for lwt.react
Ignore-this: 2996dbb79eb53b16b7a89f1e5ebdf83

darcs-hash:20100628121027-1b86b-07ab4694e0cc302a3570c541b66fe7dcd0363639

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -516,6 +516,19 @@ else
     exit 1
 fi
 
+######################################################################
+# Check lwt.react
+
+printf "%s" "Checking for lwt.react... "
+if ocamlfind query lwt.react >/dev/null 2>/dev/null; then
+    echo "found"
+else
+    echo "not found"
+    echo "Make sure that ocamlfind is in your PATH, or install lwt.react"
+    echo "(from www.ocsigen.org)"
+    exit 1
+fi
+
 
 ######################################################################
 # Check SSL
