Removing Lwt from Ocsigen tree
Lwt is now shipped as a separate package. The new darcs repos is available
at http://ocsigen.org/darcs/lwt, see http://ocsigen.org/darcsweb/ for a
web interface.

darcs-hash:20080525120828-0445d-0e0f5b07cb1fd1637a4d547f99b973dc46434cc0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -95,7 +95,7 @@ woptions=""
 
 
 # Packages to include anyway:
-requires="netstring ssl sqlite3"
+requires="lwt netstring ssl sqlite3"
 
 
 
@@ -480,6 +480,19 @@ else
 fi
 
 
+######################################################################
+# Check lwt
+
+printf "%s" "Checking for lwt... "
+if ocamlfind query lwt >/dev/null 2>/dev/null; then
+    echo "found"
+else
+    echo "not found"
+    echo "Make sure that ocamlfind is in your PATH, or install lwt"
+    echo "(from www.ocsigen.org)"
+    exit 1
+fi
+
 
 ######################################################################
 # Check SSL
@@ -788,9 +801,9 @@ PROFILING=NO
 OCAMLVERSION=$ocamlversion
 
 # Do not modify this
-LIBDIRS= -I ../lwt -I ../baselib -I ../http -I ../xmlp4 -I ../server -I ../extensions -I ../eliom
-LIBDIRS2= -I ../../lwt -I ../../baselib -I ../../http -I ../../xmlp4 -I ../../server -I ../../extensions -I ../../eliom
-LIBDIRS3= -I lwt -I baselib -I http -I xmlp4 -I server -I extensions -I eliom
+LIBDIRS= -I ../baselib -I ../http -I ../xmlp4 -I ../server -I ../extensions -I ../eliom
+LIBDIRS2= -I ../../baselib -I ../../http -I ../../xmlp4 -I ../../server -I ../../extensions -I ../../eliom
+LIBDIRS3= -I baselib -I http -I xmlp4 -I server -I extensions -I eliom
 
 _EOF_
 
