Switch to Js_of_ocaml
Ignore-this: 56ca254f8209ac1149dddb6b7fb07721

darcs-hash:20100621080837-c8b6b-9eab537ec996b7c9d78fe74618644b488716b50b

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -532,14 +532,14 @@ fi
 ######################################################################
 # Check Obrowser
 
-printf "%s" "Checking for obrowser... "
-if ocamlfind query obrowser >/dev/null 2>/dev/null; then
-    echo "found"
-else
-    echo "not found"
-    echo "Required dependency obrowser not found!"
-    exit 1
-fi
+#printf "%s" "Checking for obrowser... "
+#if ocamlfind query obrowser >/dev/null 2>/dev/null; then
+#    echo "found"
+#else
+#    echo "not found"
+#    echo "Required dependency obrowser not found!"
+#    exit 1
+#fi
 
 ######################################################################
 # Check Ocamlnet
